name: sumrak-telegram-proxy

services:
  proxy:
    image: nineseconds/mtg:2
    container_name: sumrak-telegram-proxy
    restart: unless-stopped
    network_mode: host
    command: ["simple-run", "0.0.0.0:443", "REPLACE_WITH_EE_FAKETLS_SECRET"]
