name: sumrak-telegram-proxy

services:
  proxy:
    image: telegrammessenger/proxy:latest
    container_name: sumrak-telegram-proxy
    restart: unless-stopped
    environment:
      SECRET: "REPLACE_WITH_32_HEX_SECRET_WITHOUT_DD"
    ports:
      - "443:443"
